import Layout from '@/components/Templates/Layout/Layout';
import { Box } from '@mui/material';
import Notes from '../src/components/Templates/Notes/Notes';
import Head from 'next/head';
export default function Home() {
	return (
		<>
			<Head>
				<title>Note Keeper</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Box mt={4}>
					<Notes />
				</Box>
			</Layout>
		</>
	);
}
