import Button from '@/components/Atoms/Button/Button';
import Icon from '@/components/Atoms/Icons/Icon';
import Card from '@/components/molicules/Card/Card';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main></main>
		</>
	);
}
